version: "3.8"
services:
  postgresdb:
    image: postgres:14.1-alpine
    container_name: user-management-database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=user-management
    ports:
      - "5432:5432"
